### ISSUE TITLE
Hey there,where can i find this app? 

### ISSUE THREAD

**Issue by Aruraka** [Luzivog/WebtoonReader#1]

**Comment by Luzivog** [comment]
Hello! I'm still working on it, will keep you updated!

**Comment by Aruraka** [comment]
> Hello! I'm still working on it, will keep you updated!

Hey btw do u have discord? Where u can update me about this app?nd can we search webtoons by alphabet nd genres too in this app?

**Comment by Luzivog** [comment]
Hello, for copyright reasons I won't be publishing this app. It's for personal use but feel free to look into the code!
